# Generated by Django 6.0 on 2025-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
